# ──────────────────────────────────────────────────────────────
# Base de conhecimento para heurística local
# ──────────────────────────────────────────────────────────────

_CONHECIMENTO_AEREO = {
    # destino -> lista de dados por rota popular
    "lisboa": [
        {
            "companhia": "TAP Air Portugal",
            "escalas": 0,
            "duracao": "9h00",
            "preco_base": 3200,
            "hub": "GRU",
        },
        {
            "companhia": "LATAM Airlines",
            "escalas": 1,
            "duracao": "14h30",
            "preco_base": 2800,
            "hub": "GRU",
        },
        {
            "companhia": "Iberia",
            "escalas": 1,
            "duracao": "15h00",
            "preco_base": 2600,
            "hub": "GRU",
        },
        {
            "companhia": "Air Europa",
            "escalas": 1,
            "duracao": "16h00",
            "preco_base": 2400,
            "hub": "GRU",
        },
    ],
    "paris": [
        {
            "companhia": "Air France",
            "escalas": 0,
            "duracao": "11h00",
            "preco_base": 3800,
            "hub": "GRU",
        },
        {
            "companhia": "LATAM Airlines",
            "escalas": 1,
            "duracao": "15h00",
            "preco_base": 3200,
            "hub": "GRU",
        },
        {
            "companhia": "Iberia",
            "escalas": 1,
            "duracao": "16h30",
            "preco_base": 3000,
            "hub": "GRU",
        },
    ],
    "nova york": [
        {
            "companhia": "LATAM Airlines",
            "escalas": 0,
            "duracao": "10h00",
            "preco_base": 3500,
            "hub": "GRU",
        },
        {
            "companhia": "American Airlines",
            "escalas": 0,
            "duracao": "10h30",
            "preco_base": 3600,
            "hub": "GRU",
        },
        {
            "companhia": "Delta Airlines",
            "escalas": 1,
            "duracao": "14h00",
            "preco_base": 3100,
            "hub": "GRU",
        },
    ],
    "miami": [
        {
            "companhia": "LATAM Airlines",
            "escalas": 0,
            "duracao": "7h30",
            "preco_base": 2200,
            "hub": "GRU",
        },
        {
            "companhia": "American Airlines",
            "escalas": 0,
            "duracao": "8h00",
            "preco_base": 2400,
            "hub": "GRU",
        },
        {
            "companhia": "Gol",
            "escalas": 0,
            "duracao": "8h30",
            "preco_base": 2100,
            "hub": "GRU",
        },
    ],
    "buenos aires": [
        {
            "companhia": "LATAM Airlines",
            "escalas": 0,
            "duracao": "3h00",
            "preco_base": 900,
            "hub": "GRU",
        },
        {
            "companhia": "Aerolíneas Argentinas",
            "escalas": 0,
            "duracao": "3h15",
            "preco_base": 850,
            "hub": "GRU",
        },
        {
            "companhia": "Gol",
            "escalas": 0,
            "duracao": "3h30",
            "preco_base": 780,
            "hub": "GRU",
        },
    ],
    "cancún": [
        {
            "companhia": "LATAM Airlines",
            "escalas": 1,
            "duracao": "9h00",
            "preco_base": 2800,
            "hub": "GRU",
        },
        {
            "companhia": "Avianca",
            "escalas": 1,
            "duracao": "10h00",
            "preco_base": 2500,
            "hub": "GRU",
        },
    ],
    "roma": [
        {
            "companhia": "Alitalia / ITA Airways",
            "escalas": 0,
            "duracao": "12h00",
            "preco_base": 3700,
            "hub": "GRU",
        },
        {
            "companhia": "LATAM Airlines",
            "escalas": 1,
            "duracao": "16h00",
            "preco_base": 3200,
            "hub": "GRU",
        },
        {
            "companhia": "Iberia",
            "escalas": 1,
            "duracao": "15h00",
            "preco_base": 3100,
            "hub": "GRU",
        },
    ],
    "default": [
        {
            "companhia": "LATAM Airlines",
            "escalas": 1,
            "duracao": "12h00",
            "preco_base": 2500,
            "hub": "GRU",
        },
        {
            "companhia": "Gol",
            "escalas": 1,
            "duracao": "13h00",
            "preco_base": 2200,
            "hub": "GRU",
        },
        {
            "companhia": "Azul",
            "escalas": 1,
            "duracao": "11h30",
            "preco_base": 2300,
            "hub": "VCP",
        },
    ],
}

_HUBS_POR_ORIGEM = {
    "são paulo": "GRU",
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "brasília": "BSB",
    "brasilia": "BSB",
    "teresina": "THE",
    "fortaleza": "FOR",
    "recife": "REC",
    "salvador": "SSA",
    "manaus": "MAO",
    "porto alegre": "POA",
    "curitiba": "CWB",
    "belo horizonte": "CNF",
    "default": "GRU",
}

_CONHECIMENTO_HOTEL = {
    "lisboa": {
        "regioes_recomendadas": [
            "Baixa-Chiado",
            "Belém",
            "Alfama",
            "Príncipe Real",
            "Parque das Nações",
        ],
        "hoteis": [
            {
                "nome": "Hotel Altis Belém",
                "bairro": "Belém",
                "categoria": "5 estrelas",
                "preco_diaria": 650,
                "avaliacao": "9.2/10",
                "destaques": [
                    "Piscina",
                    "Vista para o Tejo",
                    "Spa",
                    "Restaurante gourmet",
                ],
            },
            {
                "nome": "Lisboa Carmo Hotel",
                "bairro": "Chiado",
                "categoria": "4 estrelas",
                "preco_diaria": 280,
                "avaliacao": "8.9/10",
                "destaques": [
                    "Centro histórico",
                    "Café da manhã",
                    "Localização excelente",
                ],
            },
            {
                "nome": "Hotel ZENIT Lisboa",
                "bairro": "Baixa",
                "categoria": "3 estrelas",
                "preco_diaria": 160,
                "avaliacao": "8.2/10",
                "destaques": ["Boa localização", "Custo-benefício", "Próximo ao metrô"],
            },
            {
                "nome": "Bairro Alto Hotel",
                "bairro": "Bairro Alto",
                "categoria": "5 estrelas",
                "preco_diaria": 580,
                "avaliacao": "9.4/10",
                "destaques": [
                    "Boutique",
                    "Vista panorâmica",
                    "Restaurante com estrela Michelin",
                ],
            },
        ],
    },
    "paris": {
        "regioes_recomendadas": [
            "Le Marais",
            "Saint-Germain-des-Prés",
            "Montmartre",
            "Châtelet",
            "Opera",
        ],
        "hoteis": [
            {
                "nome": "Hotel des Arts Montmartre",
                "bairro": "Montmartre",
                "categoria": "3 estrelas",
                "preco_diaria": 220,
                "avaliacao": "8.5/10",
                "destaques": [
                    "Vista para Sacré-Cœur",
                    "Café da manhã",
                    "Ambiente artístico",
                ],
            },
            {
                "nome": "Hotel Le Marais Bastille",
                "bairro": "Le Marais",
                "categoria": "4 estrelas",
                "preco_diaria": 320,
                "avaliacao": "8.8/10",
                "destaques": ["Centro histórico", "Próximo ao metrô", "Wi-Fi gratuito"],
            },
            {
                "nome": "Ibis Paris Gare de Lyon",
                "bairro": "Lyon",
                "categoria": "2 estrelas",
                "preco_diaria": 140,
                "avaliacao": "7.8/10",
                "destaques": [
                    "Econômico",
                    "Bem localizado",
                    "Fácil acesso ao transporte",
                ],
            },
        ],
    },
    "nova york": {
        "regioes_recomendadas": [
            "Midtown Manhattan",
            "Times Square",
            "Upper East Side",
            "Brooklyn",
            "Chelsea",
        ],
        "hoteis": [
            {
                "nome": "The Westin New York at Times Square",
                "bairro": "Times Square",
                "categoria": "4 estrelas",
                "preco_diaria": 480,
                "avaliacao": "8.6/10",
                "destaques": ["Centro de tudo", "Academia", "Vista para Times Square"],
            },
            {
                "nome": "Pod 51 Hotel",
                "bairro": "Midtown East",
                "categoria": "3 estrelas",
                "preco_diaria": 220,
                "avaliacao": "8.1/10",
                "destaques": ["Design moderno", "Custo-benefício", "Próximo ao metrô"],
            },
            {
                "nome": "The Standard, High Line",
                "bairro": "Chelsea",
                "categoria": "4 estrelas",
                "preco_diaria": 380,
                "avaliacao": "8.9/10",
                "destaques": [
                    "Design icônico",
                    "Vista do Rio Hudson",
                    "Restaurante rooftop",
                ],
            },
        ],
    },
    "miami": {
        "regioes_recomendadas": [
            "South Beach",
            "Brickell",
            "Downtown Miami",
            "Wynwood",
            "Coral Gables",
        ],
        "hoteis": [
            {
                "nome": "Faena Hotel Miami Beach",
                "bairro": "South Beach",
                "categoria": "5 estrelas",
                "preco_diaria": 780,
                "avaliacao": "9.3/10",
                "destaques": ["Praia privativa", "Spa luxuoso", "Arte de vanguarda"],
            },
            {
                "nome": "Kimpton Angler's Hotel",
                "bairro": "South Beach",
                "categoria": "4 estrelas",
                "preco_diaria": 340,
                "avaliacao": "8.7/10",
                "destaques": ["Piscina", "Bar na cobertura", "A 100m da praia"],
            },
            {
                "nome": "Hotel Urbano",
                "bairro": "Brickell",
                "categoria": "3 estrelas",
                "preco_diaria": 180,
                "avaliacao": "8.0/10",
                "destaques": ["Piscina", "Café da manhã", "Custo-benefício"],
            },
        ],
    },
    "buenos aires": {
        "regioes_recomendadas": [
            "Palermo",
            "San Telmo",
            "Recoleta",
            "Puerto Madero",
            "Belgrano",
        ],
        "hoteis": [
            {
                "nome": "Hotel Faena Buenos Aires",
                "bairro": "Puerto Madero",
                "categoria": "5 estrelas",
                "preco_diaria": 420,
                "avaliacao": "9.1/10",
                "destaques": ["Piscina aquecida", "Spa", "Vista para o Rio da Prata"],
            },
            {
                "nome": "Palermo Soho Suites",
                "bairro": "Palermo",
                "categoria": "4 estrelas",
                "preco_diaria": 180,
                "avaliacao": "8.8/10",
                "destaques": ["Terraço", "Café da manhã incluso", "Bairro badalado"],
            },
            {
                "nome": "Hostel Suites San Telmo",
                "bairro": "San Telmo",
                "categoria": "2 estrelas",
                "preco_diaria": 70,
                "avaliacao": "8.2/10",
                "destaques": ["Econômico", "Bairro histórico", "Ótima localização"],
            },
        ],
    },
    "roma": {
        "regioes_recomendadas": [
            "Centro Storico",
            "Trastevere",
            "Prati",
            "Termini",
            "Testaccio",
        ],
        "hoteis": [
            {
                "nome": "Hotel de la Minerve",
                "bairro": "Centro Storico",
                "categoria": "5 estrelas",
                "preco_diaria": 620,
                "avaliacao": "9.0/10",
                "destaques": [
                    "Terraço panorâmico",
                    "A 200m do Panthéon",
                    "Restaurante excelente",
                ],
            },
            {
                "nome": "Hotel Artemide",
                "bairro": "Termini",
                "categoria": "4 estrelas",
                "preco_diaria": 220,
                "avaliacao": "8.7/10",
                "destaques": [
                    "Café da manhã farto",
                    "Spa e piscina",
                    "Próximo à estação central",
                ],
            },
            {
                "nome": "Trastevere Charming House",
                "bairro": "Trastevere",
                "categoria": "3 estrelas",
                "preco_diaria": 150,
                "avaliacao": "8.4/10",
                "destaques": [
                    "Bairro romântico",
                    "Custo-benefício",
                    "Restaurantes na porta",
                ],
            },
        ],
    },
    "default": {
        "regioes_recomendadas": [
            "Centro histórico",
            "Área turística principal",
            "Próximo ao transporte público",
        ],
        "hoteis": [
            {
                "nome": "Grand Hotel Centro",
                "bairro": "Centro",
                "categoria": "4 estrelas",
                "preco_diaria": 350,
                "avaliacao": "8.5/10",
                "destaques": ["Centralizado", "Café da manhã", "Próximo às atrações"],
            },
            {
                "nome": "City Comfort Hotel",
                "bairro": "Área Central",
                "categoria": "3 estrelas",
                "preco_diaria": 200,
                "avaliacao": "8.0/10",
                "destaques": ["Custo-benefício", "Boa localização", "Wi-Fi"],
            },
            {
                "nome": "Budget Inn Express",
                "bairro": "Zona Turística",
                "categoria": "2 estrelas",
                "preco_diaria": 120,
                "avaliacao": "7.5/10",
                "destaques": ["Econômico", "Café da manhã simples"],
            },
        ],
    },
}

# ──────────────────────────────────────────────────────────────
# Base de conhecimento turístico
# ──────────────────────────────────────────────────────────────

_PONTOS_TURISTICOS = {
    "lisboa": [
        {
            "nome": "Torre de Belém",
            "categoria": "histórico",
            "bairro": "Belém",
            "tempo": "1h30",
            "prioridade": 1,
        },
        {
            "nome": "Mosteiro dos Jerónimos",
            "categoria": "histórico",
            "bairro": "Belém",
            "tempo": "2h00",
            "prioridade": 2,
        },
        {
            "nome": "Museu Nacional do Azulejo",
            "categoria": "cultural",
            "bairro": "Santa Apolónia",
            "tempo": "2h00",
            "prioridade": 3,
        },
        {
            "nome": "Alfama e Castelo de São Jorge",
            "categoria": "histórico",
            "bairro": "Alfama",
            "tempo": "3h00",
            "prioridade": 4,
        },
        {
            "nome": "Praça do Comércio",
            "categoria": "cultural",
            "bairro": "Baixa",
            "tempo": "1h00",
            "prioridade": 5,
        },
        {
            "nome": "Parque das Nações",
            "categoria": "entretenimento",
            "bairro": "Parque das Nações",
            "tempo": "3h00",
            "prioridade": 6,
        },
        {
            "nome": "Bairro Alto & Chiado",
            "categoria": "gastronômico",
            "bairro": "Chiado",
            "tempo": "2h00",
            "prioridade": 7,
        },
        {
            "nome": "LX Factory",
            "categoria": "cultural",
            "bairro": "Alcântara",
            "tempo": "2h00",
            "prioridade": 8,
        },
        {
            "nome": "Palácio Nacional de Sintra",
            "categoria": "histórico",
            "bairro": "Sintra (excursão)",
            "tempo": "4h00",
            "prioridade": 9,
        },
        {
            "nome": "Cabo da Roca",
            "categoria": "natureza",
            "bairro": "Sintra (excursão)",
            "tempo": "1h30",
            "prioridade": 10,
        },
    ],
    "paris": [
        {
            "nome": "Torre Eiffel",
            "categoria": "histórico",
            "bairro": "Champ-de-Mars",
            "tempo": "2h00",
            "prioridade": 1,
        },
        {
            "nome": "Museu do Louvre",
            "categoria": "cultural",
            "bairro": "1er arrondissement",
            "tempo": "4h00",
            "prioridade": 2,
        },
        {
            "nome": "Notre-Dame de Paris",
            "categoria": "religioso",
            "bairro": "Île de la Cité",
            "tempo": "1h30",
            "prioridade": 3,
        },
        {
            "nome": "Musée d'Orsay",
            "categoria": "cultural",
            "bairro": "7e arrondissement",
            "tempo": "3h00",
            "prioridade": 4,
        },
        {
            "nome": "Arc de Triomphe & Champs-Élysées",
            "categoria": "histórico",
            "bairro": "8e arrondissement",
            "tempo": "2h00",
            "prioridade": 5,
        },
        {
            "nome": "Montmartre & Sacré-Cœur",
            "categoria": "cultural",
            "bairro": "Montmartre",
            "tempo": "2h30",
            "prioridade": 6,
        },
        {
            "nome": "Palácio de Versalhes",
            "categoria": "histórico",
            "bairro": "Versalhes (excursão)",
            "tempo": "5h00",
            "prioridade": 7,
        },
        {
            "nome": "Le Marais",
            "categoria": "gastronômico",
            "bairro": "Le Marais",
            "tempo": "2h00",
            "prioridade": 8,
        },
    ],
    "nova york": [
        {
            "nome": "Estátua da Liberdade & Ellis Island",
            "categoria": "histórico",
            "bairro": "Liberty Island",
            "tempo": "4h00",
            "prioridade": 1,
        },
        {
            "nome": "Central Park",
            "categoria": "natureza",
            "bairro": "Midtown",
            "tempo": "2h00",
            "prioridade": 2,
        },
        {
            "nome": "Times Square",
            "categoria": "entretenimento",
            "bairro": "Midtown",
            "tempo": "1h00",
            "prioridade": 3,
        },
        {
            "nome": "Metropolitan Museum of Art",
            "categoria": "cultural",
            "bairro": "Upper East Side",
            "tempo": "3h00",
            "prioridade": 4,
        },
        {
            "nome": "Empire State Building",
            "categoria": "histórico",
            "bairro": "Midtown",
            "tempo": "2h00",
            "prioridade": 5,
        },
        {
            "nome": "Brooklyn Bridge & DUMBO",
            "categoria": "histórico",
            "bairro": "Brooklyn",
            "tempo": "2h00",
            "prioridade": 6,
        },
        {
            "nome": "High Line",
            "categoria": "cultural",
            "bairro": "Chelsea",
            "tempo": "1h30",
            "prioridade": 7,
        },
        {
            "nome": "9/11 Memorial & Museum",
            "categoria": "histórico",
            "bairro": "Financial District",
            "tempo": "2h30",
            "prioridade": 8,
        },
    ],
    "miami": [
        {
            "nome": "South Beach & Ocean Drive",
            "categoria": "natureza",
            "bairro": "South Beach",
            "tempo": "3h00",
            "prioridade": 1,
        },
        {
            "nome": "Art Deco Historic District",
            "categoria": "histórico",
            "bairro": "South Beach",
            "tempo": "2h00",
            "prioridade": 2,
        },
        {
            "nome": "Wynwood Walls",
            "categoria": "cultural",
            "bairro": "Wynwood",
            "tempo": "2h00",
            "prioridade": 3,
        },
        {
            "nome": "Vizcaya Museum & Gardens",
            "categoria": "histórico",
            "bairro": "Coconut Grove",
            "tempo": "2h30",
            "prioridade": 4,
        },
        {
            "nome": "Little Havana",
            "categoria": "gastronômico",
            "bairro": "Little Havana",
            "tempo": "2h00",
            "prioridade": 5,
        },
        {
            "nome": "Everglades National Park",
            "categoria": "natureza",
            "bairro": "Everglades (excursão)",
            "tempo": "6h00",
            "prioridade": 6,
        },
    ],
    "buenos aires": [
        {
            "nome": "La Boca & Caminito",
            "categoria": "cultural",
            "bairro": "La Boca",
            "tempo": "2h00",
            "prioridade": 1,
        },
        {
            "nome": "San Telmo & Feira Antigos",
            "categoria": "cultural",
            "bairro": "San Telmo",
            "tempo": "2h30",
            "prioridade": 2,
        },
        {
            "nome": "Palácio do Congresso",
            "categoria": "histórico",
            "bairro": "Balvanera",
            "tempo": "1h30",
            "prioridade": 3,
        },
        {
            "nome": "Recoleta Cemetery",
            "categoria": "histórico",
            "bairro": "Recoleta",
            "tempo": "1h30",
            "prioridade": 4,
        },
        {
            "nome": "MALBA - Museu de Arte Latino-Americana",
            "categoria": "cultural",
            "bairro": "Palermo",
            "tempo": "2h00",
            "prioridade": 5,
        },
        {
            "nome": "Puerto Madero",
            "categoria": "gastronômico",
            "bairro": "Puerto Madero",
            "tempo": "2h00",
            "prioridade": 6,
        },
        {
            "nome": "Tango Show em San Telmo",
            "categoria": "entretenimento",
            "bairro": "San Telmo",
            "tempo": "2h30",
            "prioridade": 7,
        },
    ],
    "roma": [
        {
            "nome": "Coliseu e Fórum Romano",
            "categoria": "histórico",
            "bairro": "Centro Storico",
            "tempo": "3h00",
            "prioridade": 1,
        },
        {
            "nome": "Vaticano e Capela Sistina",
            "categoria": "religioso",
            "bairro": "Prati",
            "tempo": "4h00",
            "prioridade": 2,
        },
        {
            "nome": "Fontana di Trevi",
            "categoria": "histórico",
            "bairro": "Trevi",
            "tempo": "1h00",
            "prioridade": 3,
        },
        {
            "nome": "Panthéon",
            "categoria": "histórico",
            "bairro": "Pigna",
            "tempo": "1h30",
            "prioridade": 4,
        },
        {
            "nome": "Piazza Navona",
            "categoria": "cultural",
            "bairro": "Parione",
            "tempo": "1h00",
            "prioridade": 5,
        },
        {
            "nome": "Trastevere",
            "categoria": "gastronômico",
            "bairro": "Trastevere",
            "tempo": "2h30",
            "prioridade": 6,
        },
        {
            "nome": "Galeria Borghese",
            "categoria": "cultural",
            "bairro": "Villa Borghese",
            "tempo": "2h00",
            "prioridade": 7,
        },
        {
            "nome": "Castelo Sant'Angelo",
            "categoria": "histórico",
            "bairro": "Borgo",
            "tempo": "2h00",
            "prioridade": 8,
        },
    ],
    "default": [
        {
            "nome": "Centro Histórico da Cidade",
            "categoria": "histórico",
            "bairro": "Centro",
            "tempo": "2h00",
            "prioridade": 1,
        },
        {
            "nome": "Museu Municipal Principal",
            "categoria": "cultural",
            "bairro": "Centro",
            "tempo": "2h00",
            "prioridade": 2,
        },
        {
            "nome": "Mercado e Gastronomia Local",
            "categoria": "gastronômico",
            "bairro": "Centro",
            "tempo": "1h30",
            "prioridade": 3,
        },
        {
            "nome": "Parque ou Área Verde Principal",
            "categoria": "natureza",
            "bairro": "Área central",
            "tempo": "1h30",
            "prioridade": 4,
        },
        {
            "nome": "Mirante ou Vista Panorâmica",
            "categoria": "cultural",
            "bairro": "Ponto alto",
            "tempo": "1h00",
            "prioridade": 5,
        },
        {
            "nome": "Bairro Artístico e Cultural",
            "categoria": "cultural",
            "bairro": "Bairro Artístico",
            "tempo": "2h00",
            "prioridade": 6,
        },
    ],
}

_DICAS_GERAIS = {
    "lisboa": [
        "🚊 Use o Passe Lisboa para metrô, eléctrico e ônibus. Vale muito a pena.",
        "🍽️ Almoce entre 12h-14h nos restaurantes locais para evitar filas e pagar menos.",
        "🎭 Reserve ingressos do Mosteiro dos Jerónimos com antecedência — forma filas enormes.",
        "☀️ Julho é muito quente: leve protetor solar e hidrate-se bem.",
        "🏄 Reserve um dia para Sintra — a excursão vale cada minuto!",
    ],
    "paris": [
        "🎫 Compre o Paris Museum Pass para acesso a mais de 50 museus sem filas.",
        "🚇 O metrô parisiense é eficiente e econômico para se locomover.",
        "🥐 Pequenos bistrôs cobram menos que restaurantes turísticos. Explore!",
        "📸 A Torre Eiffel é mais bonita ao pôr do sol e iluminada à noite.",
        "🏰 Versalhes recebe milhões de turistas. Reserve com meses de antecedência.",
    ],
    "nova york": [
        "🗽 Compre ingressos para a Estátua da Liberdade com semanas de antecedência.",
        "🚇 O subway é o melhor transporte. Compre um MetroCard ilimitado.",
        "🎭 Busque bilhetes TKTS em Times Square para shows na Broadway com desconto.",
        "🌆 O Top of the Rock (30 Rock) tem vista melhor que o Empire State e menos filas.",
        "🍕 A pizza nova-iorquina de fatia é uma experiência cultural obrigatória.",
    ],
    "default": [
        "📅 Pesquise eventos locais que possam ocorrer no período da sua viagem.",
        "💊 Verifique se há necessidade de vacinas ou documentos especiais para o destino.",
        "💱 Consulte as melhores opções de câmbio antes de viajar.",
        "📱 Baixe mapas offline do destino para usar sem internet.",
        "🌤️ Verifique a previsão do tempo para os dias da viagem.",
    ],
}